CREATE TABLE followers (
  id uuid NOT NULL,
  followed TEXT NOT NULL,
  followedBy DATETIME NOT NULL,
  CONSTRAINT PK__FOLLOWERS PRIMARY KEY (id)
);

ALTER TABLE followers ADD CONSTRAINT FK__FOLLOWERS__FOLLOWED
FOREIGN KEY (followed) 
REFERENCES users (id) MATCH FULL
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE followers ADD CONSTRAINT FK__FOLLOWERS__FOLLOWEDBY
FOREIGN KEY (followedBy) 
REFERENCES users (id) MATCH FULL
ON DELETE SET NULL
ON UPDATE CASCADE;