CREATE TABLE posts (
  id uuid NOT NULL,
  description TEXT NOT NULL,
  createdAt DATETIME NOT NULL,
  userId uuid NOT NULL,
  isRepost INTEGER,
  isQuote INTEGER,
  postId uuid,
  CONSTRAINT PK__POSTS PRIMARY KEY (id)
);

ALTER TABLE posts ADD CONSTRAINT FK__USERS__POSTS
FOREIGN KEY (userId) 
REFERENCES users (id) MATCH FULL
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE posts ADD CONSTRAINT FK__POSTS__POSTS
FOREIGN KEY (postId)
REFERENCES posts (id) MATCH FULL
ON DELETE SET NULL
ON UPDATE CASCADE;